config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'html_pages#home'
  mount StripeEvent::Engine, at: '/stripe-webhooks'
  get 'password_resets/new'
  get 'password_resets/edit'
  get '/qr',            to: 'html_pages#home'
  get '/home',          to: 'html_pages#home'
  get '/about',         to: 'html_pages#about'
  get '/for_businesses', to: 'html_pages#for_businesses'
  get '/for_artists', to: 'html_pages#for_artists'
  get '/for_art_lovers', to: 'html_pages#for_art_lovers'
  get '/terms',         to: 'html_pages#terms'
  get '/privacypolicy', to: 'html_pages#privacypolicy'
  get '/cookiepolicy',  to: 'html_pages#cookiepolicy'
  get '/contact',       to: 'html_pages#contact'
  get '/search',        to: 'html_pages#search'
  get 'art',            to: 'html_pages#browse_art'
  get 'howitworks',     to: 'html_pages#howitworks'
  get 'faq',            to: 'html_pages#faq'
  get 'dpa',            to: 'html_pages#dpa'
  get '/signup',        to: 'users#new'
  get '/login',         to: 'sessions#new'
  get '/preload',       to: 'reservations#preload'
  get '/preview',       to: 'reservations#preview'
  get '/your_bookings',       to: 'reservations#your_bookings'
  get '/your_reservations',   to: 'reservations#your_reservations'
  get 'exhibitions',  to: 'reservations#current_exhibitions'
  get 'upcoming_exhibitions', to: 'reservations#upcoming_exhibitions'
  get 'past_exhibitions',     to: 'reservations#past_exhibitions'
  get 'stripe/connect', to: 'stripe#connect', as: :stripe_connect
  get 'stripe/dashboard/:user_id', to: 'stripe#dashboard', as: :stripe_dashboard
  post '/login',        to: 'sessions#create'
  delete '/logout',     to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations,     only: [:edit]
  resources :password_resets,         only: %i[new create edit update]
  resources :relationships,           only: %i[create destroy]
  resources :spaces do
    resources :reservations, only: %i[create index], shallow: true
  end
  resources :artworks do
    resources :orders, only: %i[create index], shallow: true
  end
  resources :artworks do
    member do
      delete :delete_image_attachment
    end
  end
  resources :spaces do
    member do
      delete :delete_image_attachment
    end
  end
  resources :spaces,                  only: %i[new show index create
                                               edit update destroy]
  resources :artworks,                only: %i[new show index create
                                               edit update destroy]
  resources :conversations,           only: %i[index create] do
    resources :messages,              only: %i[index create], shallow: true
  end

  resources :spaces do
    resources :reviews,               only: [:destroy], shallow: true
  end

  resources :reservations do
    resources :reviews,               only: [:create], shallow: true
  end

  resources :reservation_approvals,   only: [:edit]
  resources :reservation_rejections,  only: [:edit]

  resources :reservations do
    get 'payment', to: 'reservations#payment'
  end

  resources :orders do
    get 'payment', to: 'orders#payment'
  end

  get 'reservation_success', to: 'reservations#success'
  get 'reservation_cancel',  to: 'reservations#cancel'

  get 'order_success',       to: 'orders#success'
  get 'order_cancel',        to: 'orders#cancel'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token, :reset_token

  before_save :downcase_email
  before_create :create_activation_digest
  before_create { self.display_name = firstname + ' ' + lastname }
  before_create :create_username
  before_create { self.currency = 'gbp' }

  has_many :spaces, dependent: :destroy
  has_many :reservations, dependent: :destroy
  has_many :artworks, dependent: :destroy
  has_many :orders
  has_many :active_relationships, class_name: 'Relationship',
                                  foreign_key: 'follower_id',
                                  dependent: :destroy
  has_many :passive_relationships, class_name: 'Relationship',
                                   foreign_key: 'followed_id',
                                   dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :reviews
  has_one_attached :image

  validates :firstname, presence: true, length: { maximum: 60 }
  validates :lastname, presence: true, length: { maximum: 60 }
  validates :display_name, presence: true, length: { maximum: 60 }, allow_nil: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  validates :instagram, length: { maximum: 60 }
  validates :facebook, length: { maximum: 60 }
  validates :twitter, length: { maximum: 60 }
  validates :website, length: { maximum: 60 }
  validates :bio, length: { maximum: 1000 }
  validates :currency, length: { maximum: 3 }, presence: true, allow_nil: true
  validates :user_name, length: { maximum: 60 }, presence: true, allow_nil: true

  validates :image, content_type: { in: %w[image/jpeg image/jpg image/gif image/png], message: 'Please upload a valid file type (jpeg, gif, png).' },
                    size: { less_than: 5.megabytes, message: 'exceeds 5MB.' }

  # Returns the hash digest of the given string.
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random Token
  def self.new_token
    SecureRandom.urlsafe_base64
  end

  # Activates an Account
  def activate
    update_columns(activated: true, activated_at: Time.zone.now)
  end

  # Sends activation email.
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  # Set the password reset attributes
  def create_reset_digest
    self.reset_token = User.new_token
    update_columns(reset_digest: User.digest(reset_token), reset_sent_at: Time.zone.now)
  end

  # Sends password reset email
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?

    BCrypt::Password.new(digest).is_password?(token)
  end

  # Returns true if a password reset has expired
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  def space_feed
    followed_space = Space.where('user_id IN (?) OR user_id =?', following_ids, id)
    if followed_space.count >= 3
      followed_space
    else
      followed_space && Space.all
    end
  end

  def art_feed
    followed_art = Artwork.where('user_id IN (?) OR user_id =?', following_ids, id)
    if followed_art.count >= 3
      followed_art
    else
      followed_art && Artwork.all
    end
  end

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    following.delete(other_user)
  end

  def following?(other_user)
    following.include?(other_user)
  end

  private

  # converts email to all lower-case
  def downcase_email
    self.email = email.downcase
  end

  # Creates and assigns the activation token and digest.
  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest(activation_token)
  end

  def create_username
    self.user_name = if User.any?
                       'user_' + (User.last.id + 1).to_s
                     else
                       'user_1'
                     end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :logged_in_user,  only: %i[show index edit update destroy following followers]
  before_action :correct_user,    only: %i[edit update]
  before_action :admin_user,      only: %i[destroy index]

  def index
    @users = User.where(activated: true).paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    @spaces = @user.spaces.where(active: true).paginate(page: params[:page])
    @artworks = @user.artworks.paginate(page: params[:page])
    redirect_to root_url and return unless @user.activated?
  end

  def new
    if logged_in?
      redirect_to root_url
      flash[:warning] = "You're already signed up and logged in."
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(user_params)
    if verify_recaptcha(model: @user) && @user.save
      @user.send_activation_email
      flash[:info] = 'Please check your email to activate your account.'
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      flash[:success] = 'Profile updated'
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = 'User deleted'
    redirect_to users_url
  end

  def following
    @title = 'Following'
    @user = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = 'Followers'
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private

  def user_params
    params.require(:user).permit(:firstname, :lastname, :display_name, :email, :password,
                                 :password_confirmation, :instagram, :facebook, :twitter,
                                 :website, :bio, :marketing_consent, :currency, :image)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def gravatar_for(user, size: 80, default: 'mp')
    if user.image.attached?
      image_tag(user.image, size: size, class: 'gravatar rounded-circle')
    else
      gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
      gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?d=#{default}&s=#{size}"
      image_tag(gravatar_url, alt: user.display_name, class: 'gravatar rounded-circle')
    end
  end

  def stripe_button_link
    stripe_url = 'https://connect.stripe.com/express/oauth/authorize'
    redirect_uri = stripe_connect_url
    client_id = ENV['STRIPE_CLIENT_ID']

    "#{stripe_url}?redirect_uri=#{redirect_uri}&client_id=#{client_id}"
  end

  def needs_stripe?
    !current_user.stripe_user_id? && (current_user.spaces.where("active = ? AND for_free = ?", true, false).any? ||
    current_user.artworks.where(status: 'For Sale').any?)
  end

  def pending_reservations?
    #    current_user.spaces.each do |space|
    #      space.reservations.where("approved = ? AND rejected = ? AND payment_completed = ? AND created_at > ? AND status != ?", false, false, true, 48.hours.ago, "Payment Intent Cancelled").any?
    #    end
  end
end

app/views/users/_follow.html.erb
<%= form_with(model: current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class:"btn btn-sm btn-outline-secondary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form" class="btn-group btn-group-sm">
    <% if current_user.following?(@user) %>
      <%= render 'unfollow' %>
    <% else %>
      <%= render 'follow' %>
    <% end %>

  </div>
<% end %>

app/views/users/_send_message.html.erb
<% unless current_user?(@user) %>
  <%= link_to "Send Message", conversations_path(sender_id: current_user.id, recipient_id: @user.id),
method: 'post', class:"btn btn-sm btn-outline-secondary" %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_with(model: current_user.active_relationships.find_by(followed_id: @user.id),
              html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "Unfollow", class:"btn btn-sm btn-outline-secondary" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>&nbsp;
  <%= link_to user.display_name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete, data: { confirm: "Are you sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'Update Profile') %>

<%= form_with(model: @user, local: true, class: "needs-validation" ) do |f| %>
<%= render 'shared/error_messages', object: f.object %>
  <h1>Update Profile</h1>
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <h2>Profile Settings</h2>
      <div class="form-group">
        <%= f.label :firstname %>
        <%= f.text_field :firstname, class: "form-control", placeholder:"First Name", required: true %>
      </div>
      <div class="form-group">
        <%= f.label :lastname %>
        <%= f.text_field :lastname, class: "form-control", placeholder:"Last Name", required: true %>
      </div>

      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: "form-control", placeholder:"Email Address", required: true, disabled: true %>
        <small class="form-text text-muted">
          Please contact us if you need to update your email address.
        </small>
      </div>
      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, placeholder: "Password", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, placeholder: "Confirm Password", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :currency %>
        <%= f.select :currency, user_currencies,
        {prompt: "Currency"}, class: "form-control custom-select", required: true %>
        <small class="form-text text-muted">
          This will update the currency of all your listings.
        </small>
      </div>
      <div class="form-group">
        <div class="form-check">
          <%= f.check_box :marketing_consent, class:"form-check-input", id:"marketing" %>
          <label class="form-check-label text-muted" for="marketing">
            Opt in to receive occasional updates on spaces, artwork and exhibitions, and other announcements.
            We also don't like spam. That's why we make it easy for you to updated your email preferences or unsubscribe at anytime.
          </label>
        </div>
      </div>

      <h2>Public Profile</h2>
      <div class="form-group">
        <%= f.label :instagram %>
        <%= f.text_field :instagram, class: "form-control", placeholder:"instagram handle, e.g. exhybyt" %>
      </div>
      <div class="form-group">
        <%= f.label :facebook %>
        <%= f.text_field :facebook, class: "form-control", placeholder:"facebook handle, e.g. exhybyt" %>
      </div>
      <div class="form-group">
        <%= f.label :twitter %>
        <%= f.text_field :twitter, class: "form-control", placeholder:"twitter handle, e.g. exhybyt" %>
      </div>
      <div class="form-group">
        <%= f.label :website %>
        <%= f.text_field :website, class: "form-control", placeholder:"website, e.g. www.exhybyt.com" %>
      </div>
      <div class="form-group">
        <%= f.label :display_name %>
        <%= f.text_field :display_name, class: "form-control", placeholder:"Display Name", required: true %>
        <small class="form-text text-muted">
          If you represent an organisation, you can use its name as your display name. Display name is shown to other users instead of your first and last name.
        </small>
      </div>
      <div class="form-group">
        <%= f.label :bio %>
        <%= f.text_area :bio, class: "form-control", placeholder:"Your bio", maxlength:1000 %>
      </div>
      <div class="form-group">
        <%= f.label :image, "Profile Picture" %>
        <%= f.file_field :image, accept: "image/jpeg, image/gif, image/png" %>
      </div>
    </div>
  </div>

  <div class="row center">
    <div class="col-md-12">
      <div class="form-group">
        <%= f.submit "Save Changes", class: "btn btn-primary" %>
      </div>
    </div>
  </div>

  <div class="row mt-2">
    <div class="col-md-6 offset-md-5">
      <div class="row">
        <div class="container mb-2">
          <%= gravatar_for @user, size:50 %>
          <% if @user.image.attached? %>
            Profile Picture
          <% else %>
            <a href="https://gravatar.com/emails" target="_blank" >Change Avatar</a>
          <% end %>
        </div>
      </div>
      <div class="row">
        <div class="container">
          <i class="fab fa-stripe fa-3x align-middle text-primary"></i>
          <% if @user.stripe_user_id %>
            <%= link_to "Dashboard", stripe_dashboard_path(@user.id),class:"align-middle", target: :_blank %>
          <% else %>
            <%= link_to "Connect with Stripe", stripe_button_link, class:"align-middle" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

<% end %>

<script type="text/javascript">
  $("#space_image").bind("change", function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
    alert("image cannot exceet 5MB. Please choose a smaller file.");
    }
    $("#space_image").val("");
  });
</script>

app/views/users/index.html.erb
<% provide(:title, 'Users') %>
<h1>All Users</h1>

<%= will_paginate %>

<ul class="users">
    <%= render @users %>
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>

<div class="row">
  <div class="col-md-6 offset-md-3">
    <%= form_with(model: @user, local: true, class:"needs-validation", novalidate: true ) do |f| %>
      <h1>Sign Up</h1>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="form-group">
        <%= f.text_field :firstname, placeholder: "First Name", class: "form-control shadow-sm", required: true %>
      </div>
      <div class="form-group">
        <%= f.text_field :lastname, placeholder: "Last Name", class: "form-control shadow-sm", required: true %>
      </div>
      <div class="form-group">
        <%= f.email_field :email, placeholder: "Email", class: "form-control shadow-sm", required: true %>
      </div>
      <div class="form-group">
        <%= f.password_field :password, placeholder: "Password", class: "form-control shadow-sm", required: true %>
      </div>
      <div class="form-group">
        <%= f.password_field :password_confirmation, placeholder: "Confirm Password", class: "form-control shadow-sm", required: true %>
      </div>
      <div class="form-group">
        <%= recaptcha_tags %>
      </div>
      <div class="form-group">
        <%= f.submit "Sign Up", class: "btn btn-block btn-primary shadow-sm" %>
      </div>
      <div class="form-group">
        <div class="custom-control custom-checkbox">
          <input type="checkbox" class="custom-control-input" id="customControlValidation1" required>
          <label class="custom-control-label" for="customControlValidation1">I read and agree to EXHYBYT's <%= link_to "terms", terms_path %>, <%= link_to "privacy policy", privacypolicy_path %> and <%= link_to "cookie policy", cookiepolicy_path %>.</label>
          <div class="invalid-feedback">Please check this box to continue</div>
        </div>
      </div>
      <div class="form-group">
        <div class="custom-control custom-checkbox">
          <%= f.check_box :marketing_consent, class:"custom-control-input", id:"marketing" %>
          <label class="custom-control-label" for="marketing">
            Opt in to receive occasional updates on spaces, artwork and exhibitions, and other announcements.
            We also don't like spam. That's why we make it easy for you to updated your email preferences or unsubscribe at anytime.
          </label>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= provide(:title, @user.display_name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.display_name %>
      </h1>
      <ul class="list-unstyled text-small">
        <div class="container-center">
          <% if @user.instagram? %>
            <a href="https://www.instagram.com/<%= @user.instagram %>/" target="_blank"> <i class="fab fa-instagram text-muted"></i></a>
          <% end %>
          <% if @user.facebook? %>
            <a href="https://facebook.com/<%= @user.facebook %>" target="_blank"> <i class="fab fa-facebook-f text-muted"></i></a>
          <% end %>
          <% if @user.twitter? %>
            <a href="https://twitter.com/<%= @user.twitter %>" target="_blank"> <i class="fab fa-twitter text-muted"></i></a>
          <% end %>
          <% if @user.website? %>
            <a href="https://<%= @user.website %>" target="_blank"> <i class="fas fa-globe-europe text-muted"></i></a>
          <% end %>
        </div>
      </ul>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
    <section>
      <%= render 'follow_form' if logged_in? %>
      <%= render 'send_message' if logged_in? %>
      <% if current_user?(@user) %>
        <%= link_to "Edit Profile", edit_user_path(current_user), class:"btn btn-sm btn-outline-secondary" %>
      <% end %>
    </section>
    <%= @user.bio %>
  </aside>
  <div class="col-md-8">
    <% if @spaces.any? %>
      <h3><%= pluralize(@spaces.count, "Space") %></h3>
      <div class="card-columns">
        <%= render @spaces %>
      </div>
      <%= will_paginate @spaces %>
      <br>
    <% end %>
    <% if @artworks.any? %>
      <h3><%= pluralize(@artworks.count, "Artwork") %></h3>
      <div class="card-columns">
        <%= render @artworks %>
      </div>
      <%= will_paginate @artworks %>
    <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= link_to gravatar_for(@user), @user %>
      <h1><%= @user.display_name %></h1>
      <span><%= pluralize(@user.spaces.count, "Space") %> |
      <%= pluralize(@user.artworks.count, "Artwork") %></span>
      <span><%= link_to "view profile", @user %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user, size: 30), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>