config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'html_pages#home'
  mount StripeEvent::Engine, at: '/stripe-webhooks'
  get 'password_resets/new'
  get 'password_resets/edit'
  get '/qr',            to: 'html_pages#home'
  get '/home',          to: 'html_pages#home'
  get '/about',         to: 'html_pages#about'
  get '/for_businesses', to: 'html_pages#for_businesses'
  get '/for_artists', to: 'html_pages#for_artists'
  get '/for_art_lovers', to: 'html_pages#for_art_lovers'
  get '/terms',         to: 'html_pages#terms'
  get '/privacypolicy', to: 'html_pages#privacypolicy'
  get '/cookiepolicy',  to: 'html_pages#cookiepolicy'
  get '/contact',       to: 'html_pages#contact'
  get '/search',        to: 'html_pages#search'
  get 'art',            to: 'html_pages#browse_art'
  get 'howitworks',     to: 'html_pages#howitworks'
  get 'faq',            to: 'html_pages#faq'
  get 'dpa',            to: 'html_pages#dpa'
  get '/signup',        to: 'users#new'
  get '/login',         to: 'sessions#new'
  get '/preload',       to: 'reservations#preload'
  get '/preview',       to: 'reservations#preview'
  get '/your_bookings',       to: 'reservations#your_bookings'
  get '/your_reservations',   to: 'reservations#your_reservations'
  get 'exhibitions',  to: 'reservations#current_exhibitions'
  get 'upcoming_exhibitions', to: 'reservations#upcoming_exhibitions'
  get 'past_exhibitions',     to: 'reservations#past_exhibitions'
  get 'stripe/connect', to: 'stripe#connect', as: :stripe_connect
  get 'stripe/dashboard/:user_id', to: 'stripe#dashboard', as: :stripe_dashboard
  post '/login',        to: 'sessions#create'
  delete '/logout',     to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations,     only: [:edit]
  resources :password_resets,         only: %i[new create edit update]
  resources :relationships,           only: %i[create destroy]
  resources :spaces do
    resources :reservations, only: %i[create index], shallow: true
  end
  resources :artworks do
    resources :orders, only: %i[create index], shallow: true
  end
  resources :artworks do
    member do
      delete :delete_image_attachment
    end
  end
  resources :spaces do
    member do
      delete :delete_image_attachment
    end
  end
  resources :spaces,                  only: %i[new show index create
                                               edit update destroy]
  resources :artworks,                only: %i[new show index create
                                               edit update destroy]
  resources :conversations,           only: %i[index create] do
    resources :messages,              only: %i[index create], shallow: true
  end

  resources :spaces do
    resources :reviews,               only: [:destroy], shallow: true
  end

  resources :reservations do
    resources :reviews,               only: [:create], shallow: true
  end

  resources :reservation_approvals,   only: [:edit]
  resources :reservation_rejections,  only: [:edit]

  resources :reservations do
    get 'payment', to: 'reservations#payment'
  end

  resources :orders do
    get 'payment', to: 'orders#payment'
  end

  get 'reservation_success', to: 'reservations#success'
  get 'reservation_cancel',  to: 'reservations#cancel'

  get 'order_success',       to: 'orders#success'
  get 'order_cancel',        to: 'orders#cancel'
end

app/views/shared/_art_feed.html.erb
<% if @art_feed_items.any? %>
  <h1>Artwork</h1>
  <h2><%= link_to "Browse all art", art_path, class: "text-muted" %></h2>
  <div class="card-columns">
    <%= render @art_feed_items.take(3) %>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_space_feed.html.erb
<% if @space_feed_items.any? %>
  <h1>Featured Spaces</h1>
  <h2><%= link_to "Discover more spaces", search_path, class: "text-muted" %></h2>
  <div class="card-columns">
    <%= render @space_feed_items.take(3) %>
  </div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.display_name %></h1>
<span><%= link_to "view profile", current_user %></span>
<span><%= pluralize(current_user.spaces.count, "space") %></span>
<span><%= pluralize(current_user.artworks.count, "artwork") %></span>