config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'html_pages#home'
  mount StripeEvent::Engine, at: '/stripe-webhooks'
  get 'password_resets/new'
  get 'password_resets/edit'
  get '/qr',            to: 'html_pages#home'
  get '/home',          to: 'html_pages#home'
  get '/about',         to: 'html_pages#about'
  get '/for_businesses', to: 'html_pages#for_businesses'
  get '/for_artists', to: 'html_pages#for_artists'
  get '/for_art_lovers', to: 'html_pages#for_art_lovers'
  get '/terms',         to: 'html_pages#terms'
  get '/privacypolicy', to: 'html_pages#privacypolicy'
  get '/cookiepolicy',  to: 'html_pages#cookiepolicy'
  get '/contact',       to: 'html_pages#contact'
  get '/search',        to: 'html_pages#search'
  get 'art',            to: 'html_pages#browse_art'
  get 'howitworks',     to: 'html_pages#howitworks'
  get 'faq',            to: 'html_pages#faq'
  get 'dpa',            to: 'html_pages#dpa'
  get '/signup',        to: 'users#new'
  get '/login',         to: 'sessions#new'
  get '/preload',       to: 'reservations#preload'
  get '/preview',       to: 'reservations#preview'
  get '/your_bookings',       to: 'reservations#your_bookings'
  get '/your_reservations',   to: 'reservations#your_reservations'
  get 'exhibitions',  to: 'reservations#current_exhibitions'
  get 'upcoming_exhibitions', to: 'reservations#upcoming_exhibitions'
  get 'past_exhibitions',     to: 'reservations#past_exhibitions'
  get 'stripe/connect', to: 'stripe#connect', as: :stripe_connect
  get 'stripe/dashboard/:user_id', to: 'stripe#dashboard', as: :stripe_dashboard
  post '/login',        to: 'sessions#create'
  delete '/logout',     to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations,     only: [:edit]
  resources :password_resets,         only: %i[new create edit update]
  resources :relationships,           only: %i[create destroy]
  resources :spaces do
    resources :reservations, only: %i[create index], shallow: true
  end
  resources :artworks do
    resources :orders, only: %i[create index], shallow: true
  end
  resources :artworks do
    member do
      delete :delete_image_attachment
    end
  end
  resources :spaces do
    member do
      delete :delete_image_attachment
    end
  end
  resources :spaces,                  only: %i[new show index create
                                               edit update destroy]
  resources :artworks,                only: %i[new show index create
                                               edit update destroy]
  resources :conversations,           only: %i[index create] do
    resources :messages,              only: %i[index create], shallow: true
  end

  resources :spaces do
    resources :reviews,               only: [:destroy], shallow: true
  end

  resources :reservations do
    resources :reviews,               only: [:create], shallow: true
  end

  resources :reservation_approvals,   only: [:edit]
  resources :reservation_rejections,  only: [:edit]

  resources :reservations do
    get 'payment', to: 'reservations#payment'
  end

  resources :orders do
    get 'payment', to: 'orders#payment'
  end

  get 'reservation_success', to: 'reservations#success'
  get 'reservation_cancel',  to: 'reservations#cancel'

  get 'order_success',       to: 'orders#success'
  get 'order_cancel',        to: 'orders#cancel'
end

app/views/layouts/_cookie_banner.html.erb
<script
  type="text/javascript"
  src="https://app.termly.io/embed.min.js"
  data-auto-block="off"
  data-website-uuid="e323524f-fe54-45ca-9629-4302abe93d76"
  ></script>

app/views/layouts/_footer.html.erb
<footer class="container">
  <div class="row">
    <div class="col-12 col-md center">
      <%= image_tag asset_path("favicon.png"), class:"mb-2", alt:"", width:"100", height:"100" %>
      <small class="d-block mb-3 text-muted">&copy; <%= Date.today.year %> EXHYBYT</small>
    </div>
    <div class="col-6 col-md">
      <h5>How it works</h5>
      <ul class="list-unstyled text-small">
        <li><%= link_to "For Businesses", for_businesses_path, class:"text-muted" %></li>
        <li><%= link_to "For Art Lovers", for_art_lovers_path, class:"text-muted" %></li>
        <li><%= link_to "For Artists", for_artists_path, class:"text-muted" %></li>
        <li><%= link_to "FAQs", faq_path, class:"text-muted" %></li>
      </ul>
    </div>
    <div class="col-6 col-md">
      <h5>Features</h5>
      <ul class="list-unstyled text-small">
        <li><%= link_to "Current Exhibitions", exhibitions_path, class:"text-muted" %></li>
        <li><%= link_to "Future Exhibitions", upcoming_exhibitions_path, class:"text-muted" %></li>
        <li><%= link_to "Find Space", search_path, class:"text-muted" %></li>
        <li><%= link_to "Browse Art", art_path, class:"text-muted" %></li>
        <% if logged_in? %>
          <li><%= link_to "Add Art", new_artwork_path, class:"text-muted" %></li>
          <li><%= link_to "Add Space", new_space_path, class:"text-muted" %></li>
        <% end %>
      </ul>
    </div>
    <% if logged_in? %>
      <div class="col-6 col-md">
        <h5>Your...</h5>
        <ul class="list-unstyled text-small">
          <li><%= link_to "Artwork", artworks_path, class:"text-muted" %></li>
          <li><%= link_to "Spaces", spaces_path, class:"text-muted" %></li>
          <li><%= link_to "Bookings", your_bookings_path, class:"text-muted" %></li>
          <li><%= link_to "Reservations", your_reservations_path, class:"text-muted" %></li>
          <li><%= link_to "Profile", current_user, class:"text-muted" %></li>
          <li><%= link_to "Settings", edit_user_path(current_user), class:"text-muted" %></li>
        </ul>
      </div>
    <% else %>
      <div class="col-6 col-md">
        <h5>Join us</h5>
        <ul class="list-unstyled text-small">
          <li><%= link_to "Log In", login_path, class:"text-muted" %></li>
          <li><%= link_to "Sign Up", signup_path, class:"text-muted" %></li>
        </ul>
      </div>
    <% end %>
    <div class="col-6 col-md">
      <h5>EXHYBYT</h5>
      <ul class="list-unstyled text-small">
        <li><%= link_to "Contact", contact_path, class:"text-muted" %></li>
        <li><%= link_to "About", about_path, class:"text-muted" %></li>
        <div class="container-center">
          <a href="https://www.instagram.com/exhybyt/" target="_blank"> <i class="fab fa-instagram text-muted"></i></a>
          <a href="https://facebook.com/exhybyt" target="_blank"> <i class="fab fa-facebook-f text-muted"></i></a>
          <a href="https://twitter.com/exhybyt" target="_blank"> <i class="fab fa-twitter text-muted"></i></a>
        </div>
      </ul>
    </div>
  </div>
</footer>

<footer class="footer mt-auto py-3">
  <div class="container center">
    <span class="text-muted">
      <%= link_to "Terms", terms_path, class:"text-muted" %> |
      <%= link_to "Cookie Policy", cookiepolicy_path, class:"text-muted" %> |
      <%= link_to "Privacy Policy", privacypolicy_path, class:"text-muted" %> |
        <a class="text-muted" href="https://app.termly.io/notify/8df66e0c-e37a-4958-bf91-a2f044200ae3">
        Do not sell my info
      </a>
    </span>
  </div>
</footer>

app/views/layouts/_howitworks.html.erb
<div class="jumbotron">
  <h1>How it works</h1>
  <div class="container center">
    <div class="row">
      <div class="col-lg-4">
        <i class="fa fa-store fa-2x text-muted mt-5"></i>
        <h2>For Businesses</h2>
        <p class="center">Easily rent out the spare wall space in your business and generate an additional revenue stream while showing beautiful artwork.</p>
        <%= link_to "Find out more", for_businesses_path, class: "btn btn-secondary" %>
      </div>
      <div class="col-lg-4">
        <i class="fa fa-images fa-2x text-muted mt-5"></i>
        <h2>For Artists</h2>
        <p class="center">No matter if you are an emerging artist or a passionate photographer, it has never been easier to find a place to show your artwork and photography.</p>
        <%= link_to "Find out more", for_artists_path, class: "btn btn-secondary" %>
      </div>
      <div class="col-lg-4">
        <i class="fa fa-shopping-bag fa-2x text-muted mt-5"></i>
        <h2>For Art Lovers</h2>
        <p class="center">You can easily find the art you saw exhibited via QR Code (COMING SOON). You can also discover new artists and their exhibitions.</p>
        <%= link_to "Find out more", art_path, class: "btn btn-secondary" %>
      </div>
    </div>
  </div>
  <h2 class="mt-5"><%= link_to "FAQs", faq_path, class: "text-muted" %></h2>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-white sticky-top">
  <a class="navbar-brand" href="<%= root_path %>">
    <%= image_tag asset_path("favicon.png"), width:"30", height:"30", class:"d-inline-block align-top" %>
    EXHYBYT</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "About", about_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "How it works", howitworks_path, class: "nav-link" %>
      </li>
    </ul>
    <ul class="navbar-nav navbar-right">
      <% if logged_in? %>
        <% if needs_stripe? || pending_reservations? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown" href="current_user" id="Notifications" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: Tomato">
              <i class="far fa-bell"></i>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <% if needs_stripe? %>
                <%= link_to "Connect with Stripe to accept payments", stripe_button_link, class:"dropdown-item" %>
              <% elsif pending_reservations? %>
                <%= link_to "Approve booking requests", your_reservations_path, class:"dropdown-item" %>
              <% end %>
            </div>
          </li>
        <% end %>

        <li class="nav-item">
          <%= link_to conversations_path, class:"nav-link" do %>
            <span class="fa-layers fa-fw">
              <i class="far fa-envelope"></i>
              <% Conversation.involving(current_user).each do |conversation| %>
                <% if !conversation.unread_message_count(current_user).zero? %>
                  <span class="fa-layers-counter fa-2x" style="background:Tomato">
                    <%= conversation.unread_message_count(current_user) %>
                  </span>
                <% end %>
              <% end %>
            </span>
          <% end %>
        </li>

        <li class="nav-item">
          <%= link_to "Add Art", new_artwork_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Add Space", new_space_path, class:"nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="current_user" id="Profile" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.display_name %>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Artwork", artworks_path, class:"dropdown-item" %>
            <%= link_to "Spaces", spaces_path, class:"dropdown-item" %>
            <%= link_to "Bookings", your_bookings_path, class:"dropdown-item" %>
            <%= link_to "Reservations", your_reservations_path, class:"dropdown-item" %>
            <div class="dropdown-divider"></div>
            <%= link_to "Profile", current_user, class:"dropdown-item" %>
            <%= link_to "Settings", edit_user_path(current_user), class:"dropdown-item" %>
            <%= link_to "Log out", logout_path, method: :delete, class:"dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Log in", login_path, class:"nav-link" %>
      <% end %>
    </nav>
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script scr="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
<![endif]-->

app/views/layouts/_sidebar.html.erb
<div class="col mb-3">
  <div class="flex-column">
    <div class="list-group">
      <%= link_to artworks_path, class:"list-group-item list-group-item-action#{" active" if  current_page?(artworks_path) }" do %>
        <i class="fa fa-image"></i>
        <span>Your Artwork</span>
      <% end %>

      <%= link_to spaces_path, class:"list-group-item list-group-item-action#{" active" if  current_page?(spaces_path) }" do %>
        <i class="fa fa-store"></i>
        <span>Your Spaces</span>
      <% end %>

      <%= link_to your_bookings_path, class:"list-group-item list-group-item-action#{" active" if  current_page?(your_bookings_path) }" do %>
        <i class="fa fa-book"></i>
        <span>Your Bookings</span>
      <% end %>

      <%= link_to your_reservations_path, class:"list-group-item list-group-item-action#{" active" if  current_page?(your_reservations_path) }" do %>
        <i class="fa fa-file"></i>
        <span>Your Reservations</span>
      <% end %>

      <%= link_to conversations_path, class:"list-group-item list-group-item-action#{" active" if  current_page?(conversations_path) }" do %>
        <i class="fa fa-envelope"></i>
        <span>Messages</span>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('favicon.png'), rel: 'icon', type: 'image/png', class:'rounded-circle' %>

    <script src="https://js.stripe.com/v3/"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag '//ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.min.css' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= render 'layouts/shim' %>
  </head>

  <%= render 'layouts/cookie_banner' %>
  <body class="d-flex flex-column min-vh-100">
    <%= render 'layouts/navbar' %>
    <%= yield(:pageheader) %>
    <br>
    <div class="container flex-grow-1">
      <% flash.each do | message_type, message | %>
        <div class="alert alert-<%= message_type %>">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close" >
            <span aria-hidden="true">&times;</span>
          </button>
          <%= message %>
        </div>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>